title: "tonejs-json-sequencer"
description: "tonejs-json-sequencer"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/tonejs-json-sequencer
plugins:
  - jekyll-sitemap
